### ISSUE TITLE
When the client is locked, the Create/Restore screen doesn't open

### ISSUE THREAD

**Issue by kovaletskaterina** [PitDotDev/Sourc3-Web-Client#2]
Steps to reproduce:

1. Open client.
2. Go to the "Settings" screen and press the “Lock client” button;
3. Click “Restore client or create a new one” button and then tap “I agree” on the “Restore client or create a new one” pop-up;
**Expected result:** Create/Restore screen is opened.
**Actual result:** The authorization screen is opened.
![2022-03-24_16-35-35](https://user-images.githubusercontent.com/83376495/160097772-2cee1d9a-5a4f-4768-a40d-0f11d1b158f8.gif)

**Comment by JenkJS** [comment]
done

**Comment by kovaletskaterina** [comment]
Checked
